server:
  servlet:
    session:
      timeout: 8h
      cookie:
        http-only: true
        secure: ${SESSION_COOKIE_SECURE:false}
        same-site: lax
spring:
  application:
    name: app
  jackson:
    datatype:
      datetime:
        adjust-dates-to-context-time-zone: false
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    validate-migration-naming: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  session:
    jdbc:
      initialize-schema: never
