do $$
begin
    if exists (
        select 1 from information_schema.columns
        where table_schema='public' and table_name='clients' and column_name='id_client'
    ) then
        alter table clients rename to legacy_clients;
    end if;
    if exists (
        select 1 from information_schema.columns
        where table_schema='public' and table_name='pets' and column_name='id_pet'
    ) then
        alter table pets rename to legacy_pets;
    end if;
    if exists (
        select 1 from information_schema.columns
        where table_schema='public' and table_name='reservations' and column_name='id_reservation'
    ) then
        alter table reservations rename to legacy_reservations;
    end if;
    if to_regclass('public.reservation_pets') is not null then
        alter table reservation_pets rename to legacy_reservation_pets;
    end if;
end $$;

create table users (
    id bigint generated by default as identity primary key,
    email_normalized varchar(254) not null unique,
    password_hash varchar(255),
    email_verified_at timestamptz,
    account_type varchar(20) not null check (account_type in ('CLIENT', 'ADMIN')),
    enabled boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    version bigint not null default 0
);

create table user_external_identities (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id),
    provider varchar(30) not null,
    provider_subject varchar(255) not null,
    created_at timestamptz not null default now(),
    unique (provider, provider_subject)
);

create table clients (
    id bigint generated by default as identity primary key,
    user_id bigint not null unique references users(id),
    name varchar(120) not null,
    phone varchar(30) not null,
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    version bigint not null default 0
);

create table pets (
    id bigint generated by default as identity primary key,
    client_id bigint not null references clients(id),
    name varchar(80) not null,
    species varchar(40) not null,
    breed varchar(80),
    birthdate date,
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    version bigint not null default 0
);
create index pets_client_active_idx on pets(client_id, active);

create table email_verification_tokens (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id) on delete cascade,
    token_hash char(64) not null unique,
    expires_at timestamptz not null,
    consumed_at timestamptz,
    created_at timestamptz not null default now()
);
create index email_verification_user_idx on email_verification_tokens(user_id);

create table password_reset_tokens (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id) on delete cascade,
    token_hash char(64) not null unique,
    expires_at timestamptz not null,
    consumed_at timestamptz,
    created_at timestamptz not null default now()
);
create index password_reset_user_idx on password_reset_tokens(user_id);

create table spring_session (
    primary_id char(36) not null primary key,
    session_id char(36) not null,
    creation_time bigint not null,
    last_access_time bigint not null,
    max_inactive_interval integer not null,
    expiry_time bigint not null,
    principal_name varchar(100)
);
create unique index spring_session_ix1 on spring_session(session_id);
create index spring_session_ix2 on spring_session(expiry_time);
create index spring_session_ix3 on spring_session(principal_name);

create table spring_session_attributes (
    session_primary_id char(36) not null
        references spring_session(primary_id) on delete cascade,
    attribute_name varchar(200) not null,
    attribute_bytes bytea not null,
    primary key (session_primary_id, attribute_name)
);
