create table email_delivery_jobs (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id) on delete cascade,
    delivery_type varchar(30) not null check (delivery_type in ('VERIFICATION', 'PASSWORD_RESET')),
    state varchar(20) not null check (state in ('PENDING', 'PROCESSING', 'COMPLETED')),
    attempts integer not null default 0,
    next_attempt_at timestamptz not null,
    lease_until timestamptz,
    completed_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create index email_delivery_jobs_due_idx on email_delivery_jobs(state, next_attempt_at);
