create table services (
    id bigint generated by default as identity primary key,
    code varchar(60) not null unique,
    name varchar(100) not null,
    description varchar(500),
    active boolean not null default true,
    display_order integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    version bigint not null default 0
);

create table weekly_availability (
    id bigint generated by default as identity primary key,
    day_of_week smallint not null,
    local_start_time time not null,
    local_end_time time not null,
    active boolean not null default true,
    constraint weekly_availability_day_of_week_ck
        check (day_of_week between 1 and 7),
    constraint weekly_availability_time_order_ck
        check (local_end_time > local_start_time),
    constraint weekly_availability_interval_uq
        unique (day_of_week, local_start_time, local_end_time)
);

create table availability_blocks (
    id bigint generated by default as identity primary key,
    start_at timestamptz not null,
    end_at timestamptz not null,
    reason varchar(200),
    created_at timestamptz not null default now(),
    constraint availability_blocks_time_order_ck
        check (end_at > start_at)
);
create index availability_blocks_range_idx
    on availability_blocks(start_at, end_at);

create table reservations (
    id bigint generated by default as identity primary key,
    client_id bigint not null references clients(id),
    scheduled_start timestamptz not null,
    scheduled_end timestamptz not null,
    status varchar(20) not null,
    client_note varchar(500),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    cancelled_at timestamptz,
    cancelled_by varchar(20),
    cancellation_reason varchar(300),
    version bigint not null default 0,
    constraint reservations_status_ck check (
        status in (
            'PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', 'NO_SHOW'
        )
    ),
    constraint reservations_duration_ck
        check (scheduled_end = scheduled_start + interval '30 minutes')
);
create index reservations_client_start_idx
    on reservations(client_id, scheduled_start desc);
create index reservations_status_start_idx
    on reservations(status, scheduled_start);

create table reservation_items (
    id bigint generated by default as identity primary key,
    reservation_id bigint not null
        references reservations(id) on delete cascade,
    pet_id bigint not null references pets(id),
    service_id bigint not null references services(id),
    service_name_snapshot varchar(100) not null,
    constraint reservation_items_reservation_pet_uq
        unique (reservation_id, pet_id)
);

create table reservation_events (
    id bigint generated by default as identity primary key,
    reservation_id bigint not null
        references reservations(id) on delete cascade,
    event_type varchar(30) not null,
    actor_type varchar(20) not null,
    previous_status varchar(20),
    new_status varchar(20),
    previous_start timestamptz,
    new_start timestamptz,
    reason varchar(300),
    created_at timestamptz not null default now()
);
create index reservation_events_reservation_idx
    on reservation_events(reservation_id, created_at);

create table notifications (
    id bigint generated by default as identity primary key,
    recipient_user_id bigint not null references users(id) on delete cascade,
    type varchar(40) not null,
    title varchar(120) not null,
    body varchar(500) not null,
    reservation_id bigint references reservations(id),
    deduplication_key varchar(160) not null unique,
    read_at timestamptz,
    created_at timestamptz not null default now()
);
create index notifications_recipient_idx
    on notifications(recipient_user_id, read_at, created_at desc);
